export const articles = [
  {
    id: 1,
    title: 'Choosing Decaf Coffee - Know How The Caffeine Is Extracted',
    content: 'When it comes to enjoying a flavourful cup of coffee without the jolt of caffeine, there are four major decaffeination processes to consider. Let\'s take a closer look at each technique and the science behind them. The beans undergo steaming, releasing caffeine and making them more receptive to a solvent. Over the next ten hours, the beans are rinsed with methylene chloride or ethyl acetate to separate the caffeine from the beans. While this method raises concerns for some, it\'s important to note that brewing coffee at high temperatures significantly minimises the chances of finding any chemical residue in your cup. In this method, the beans are soaked in hot water until the water absorbs both the caffeine and other components from the beans. The water is then transferred to a separate tank where it is treated with a solvent, which selectively removes only the caffeine. The caffeine-rich solvent is skimmed off the top, never directly contacting the beans. The flavour-infused water is returned to the tank, allowing the beans to reabsorb the flavours and proteins.        ',
    img: 'https://images.unsplash.com/photo-1466019251091-1933ce15ba04?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    id: 2,
    title: 'The Secret To A Great Cup Of Coffee: How To Get The Best Brew',
    content: 'For coffee connoisseurs, the perfect cup of coffee is a matter of preference. While some enjoy elaborate beverages with steamed milk and syrups, others remain loyal to their trusty long black. No matter what you prefer, there are three components that make up the foundation of a good brew: the beans, the machine and machine maintenance. Beans It’s time to spill the beans! For the perfect cup of coffee, it\'s important to select freshly roasted coffee beans. The quality of your chosen blend will make all the difference - freshness provides an unmistakable depth and richness that stale brews simply can\'t match! Enjoy the ultimate coffee experience with our freshly roasted blends. Roasted right here in New Zealand, our coffees provide an unbeatable burst of flavour and freshness. Machine While a true workman never blames his tools, good tools are essential when it comes to making a good brew. The quality of your coffee relies on the quality of the machine you use to make it, so make sure yours stands up to the challenge. The quality brew produced by higher-end machines is leaps and bounds ahead of what can come from their cheaper counterparts - elevating flavour profiles and making an already great cup even better. If you’re spending good money on high quality coffee beans, it’s a waste if your machine isn’t up to the task. In the case of coffee machines, you get what you pay for! Cameron, the founder of the Coffee Store, recommends Vibiemme Domobar machines. Designed in New Zealand and made in Italy since 1979. Maintenance We have already discussed the importance of a good coffee machine, but it is also essential that it performs at its best. Ensure you perform regular upkeep on your machine and clean it regularly. Keep your machine clean by back-flushing it every day to remove coffee oil build-up on the brew head and wipe it down afterward. Clean all removable parts from your machine at least once a week. Every six to twelve months, you should descale your machine to remove mineral buildup that affects performance, taste, and temperature.',
    img: 'https://images.unsplash.com/photo-1533776992670-a72f4c28235e?q=80&w=1965&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    id: 3,
    title: 'Lose Weight With Coffee',
    content: 'Coffee drinkers rejoice! A new study published by Scientists from the University of Granada suggests that coffee can be an effective weight loss tool. Not only does coffee help you burn calories, but it also speeds up your metabolism so you burn more fat overall. You can even drink decaf! If you’re not into coffee, other studies suggest that green tea may also help speed up your metabolism and help you lose weight, too. Coffee Can Help Burn Fat Coffee and Weight LossScientists from the University of Granada found that drinking a strong coffee half an hour before exercising increases fat-burning! If the exercise is performed in the afternoon, the effects of caffeine are more marked than in mornings. This is due to a process known as thermogenesis: when we consume it increases body temperature and so we burn more calories than normal. When we eat food, our body converts it into energy and stores any excess as fat, says David Benton, professor of psychology at Swansea University. Coffee can help burn fat. What\'s more, coffee contains polyphenols that prevent carbohydrates from being stored as fat. Polyphenols activate genes related to thermogenesis and boost blood circulation around your abdomen where excess fat accumulates. Coffee Lowers Cholesterol A study of 21,413 men and women found that coffee drinking was associated with a lower total cholesterol level, regardless of whether people had diabetes. Why? The answer seems to be chlorogenic acid, which is an antioxidant found in coffee. Chlorogenic acid causes glucose absorption in your intestines to slow down. Slower absorption of glucose means lower blood sugar levels throughout your body. Lower blood sugar levels are good news for diabetics or anyone trying to lose weight—and helps explain why drinking caffeinated coffee is linked with a reduced risk of type 2 diabetes, heart disease and even some cancers. Coffee Boosts Metabolism Caffeine in coffee boosts metabolism, making it easier to burn fat. According to a studies people who drink caffeinated coffee burn more calories when resting than those who drink decaf. They also found that caffeine speeds up your body\'s production of norepinephrine, a hormone that plays an important role in energy expenditure. The more norepinephrine your body releases, the higher your metabolic rate is for hours after drinking coffee (even better if it\'s a nice, strong cup of espresso)',
    img: 'https://images.unsplash.com/photo-1479894127662-a987d1e38f82?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
];
